language: python
python:
  - "2.7"

sudo: required
use_chrome: true

before_install:

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - npm config set spin false
  - npm install -g npm@^2

  - git clone git://github.com/hedgeserv/ember-table.git
  - cd ember-table
  - sed -i ".bak" s/\"broccoli-es3-safe-recast\":\ \"\^1.0.0\"/\"broccoli-es3-safe-recast\":\ \"\^2\.0\.0\"/ package.json
  - npm link
  - cd ..

install:

  - npm link ember-table
  - npm install
  - bower install

before_script:

script: ./test-ci.sh


